name: Run minmyat_flowers_dataset

on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # You can specify your desired Python version

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python minmyat_flowers_dataset.py --dataset flowers_dataset --output test.png
